events { worker_connections 1024; }

http {
    # Тимчасовий конфіг тільки для отримання SSL-сертифіката
    # Використовується один раз при першому деплої

    server {
        listen 80 default_server;
        server_name _;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 "waiting for ssl...";
            add_header Content-Type text/plain;
        }
    }
}
